image: khs1994/php:8.1.1-composer-alpine
pipelines:
    pull-requests: 
        '**':
            - step:
                name: Lint
                script:
                    - composer install
                    - ./vendor/bin/php-cs-fixer fix --dry-run --diff --rules=@Symfony,@PSR12 src
                caches:
                    - composer
            - step:
                name: Test
                script:
                    - composer install  
                    - >
                        APP_ENV=test 
                        DATABASE_URL=mysql://root:let_me_in@127.0.0.1:3306/pipelines?serverVersion=8.0
                        ELASTICSEARCH_URL=http://127.0.0.1:9250/
                        ./vendor/bin/phpunit --log-junit ./test-reports/junit.xml
                    - curl -XGET 'http://localhost:9250/product/_search?pretty=true&q=*:*'
                caches:
                    - composer
                services:
                    - elasticsearch
                    - mysql
definitions: 
    services: 
        mysql:
            image: mysql/mysql-server
            variables:
                MYSQL_ROOT_PASSWORD: 'let_me_in'
                MYSQL_DATABASE: 'pipelines'
                MYSQL_ROOT_HOST: '127.0.0.1'
                MYSQL_USER: 'root'
                MYSQL_PORT: "3306"
        elasticsearch:
            image: xiting/elasticsearch-bitbucket-pipeline
            variables:
                ES_JAVA_OPTS: "-Xms512m -Xms512m"
