name: fixer
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
          tools: phpcs

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
          php_codesniffer_args: "--standard=PSR12 --ignore=*/node_modules/*"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./docker-compose.test.yml
      - run:
          docker compose -f docker-compose.test.yml run php ./wait-for-it.sh mysql:3306 &&
          docker compose -f docker-compose.test.yml run php ./wait-for-it.sh elasticsearch:9200 &&
          docker compose -f docker-compose.test.yml run php composer install &&
          docker compose -f docker-compose.test.yml run php vendor/bin/phpunit
